name: Osvezi meteo podatke 2

on:
  schedule:
      - cron: '*/30 * * * *'
        workflow_dispatch:

        jobs:
          run-sync:
              runs-on: ubuntu-latest
                  steps:
                        - name: Checkout repo
                                uses: actions/checkout@v4

                                      - name: Preuzmi podatke
                                              run: |
                                                        curl -s -u "gost:gost" "ftp://81.93.72.19/gost/MeteoMapa.json" -o MeteoMapa.json
                                                                  curl -s -u "gost:gost" "ftp://81.93.72.19/gost/RHMZmeteoautomatskestanice.json" -o RHMZmeteoautomatskestanice.json

                                                                        - name: Upload na Loopiju
                                                                                uses: SamKirkland/FTP-Deploy-Action@v4.3.5
                                                                                        with:
                                                                                                  server: ftpcluster.loopia.se
                                                                                                            username: vreme-rs.rs
                                                                                                                      password: ${{ secrets.LOOPIA_FTP_PASSWORD }}
                                                                                                                                local-dir: ./
                                                                                                                                          server-dir: /public_html/
